/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Don Flexxeo (https://sketchfab.com/Viralis)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/atat-elite-free-c662ecfeb21a4ad4b2bda173877db1f2
title: ATAT Elite (free)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const ATAT = (props) => {
  const { nodes, materials } = useGLTF("/assets/atat_elite_free.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["1002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["1002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["1003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["1003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["1003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["1001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["1001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["1001"]}
        />
      </group>
    </group>
  );
}

export default ATAT;

useGLTF.preload("/assets/atat_elite_free.glb");
