/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Adamante (https://sketchfab.com/Adamant6686)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spherical-hex-force-field-bb80cd68b5a74bd989cb18c186192c9b
title: Spherical hex force field
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Forceprojectile = (props) => {
  const { nodes, materials } = useGLTF("/assets/spherical_hex_force_field.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[8307.84, 3486.8, 4515.44]}
            rotation={[Math.PI, 0.78, 2.8]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_6_M_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_6_A_1.geometry}
            material={materials.material_1}
          />
        </group>
      </group>
    </group>
  );
}

export default Forceprojectile;

useGLTF.preload("/assets/spherical_hex_force_field.glb");
