/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MauModel (https://sketchfab.com/MauModel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/grenade-launcher-projectile-downloadable-27f55371b78d497ba0f7654dbe3c913c
title: Grenade Launcher Projectile (Downloadable)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Projectile = (props) => {
  const { nodes, materials } = useGLTF(
    "/assets/grenade_launcher_projectile_downloadable.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.01, 0.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.05}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[1816.62, 1362.69, 0.64]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.89, 0.89, 1.08]}
          >
            <group position={[-335.49, 0, -569.64]} rotation={[0, 0, -0.09]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Projectile_BULLET_0.geometry}
                material={materials.BULLET}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Projectile;

useGLTF.preload("/assets/grenade_launcher_projectile_downloadable.glb");
