/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Samize (https://sketchfab.com/samize)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/sword-of-artorias-298e29d014374a87b85b3bcdaa07a5ce
title: Sword of Artorias
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Sword = (props) => {
  const { nodes, materials } = useGLTF("/assets/sword_of_artorias.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

export default Sword;

useGLTF.preload("/assets/sword_of_artorias.glb");
