/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Javier Martín Hidalgo (https://sketchfab.com/Jj.Mmhh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laser-saber-sith-52791ba8eb284a8b9b36c6ca52ae201b
title: Laser Saber sith
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Sword = (props) => {
  const { nodes, materials } = useGLTF("/assets/laser_saber_sith.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.08, 85.34, 13.12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_negro_0.geometry}
              material={materials.negro}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_luz_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_emision_0.geometry}
              material={materials.emision}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_detalles_mango_0.geometry}
              material={materials.detalles_mango}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_plateado_0.geometry}
              material={materials.plateado}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_cuadrado_0.geometry}
              material={materials.cuadrado}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.sable_laser_botones_0.geometry}
              material={materials.botones}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default Sword;

useGLTF.preload("/assets/laser_saber_sith.glb");
