/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AFTONBLADET (https://sketchfab.com/wallander)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/darth-vader-by-makeamo-5b3371f4789c41eeaa691c9a3dfe1a96
title: Darth Vader by Makeamo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Darth = (props) => {
  const { nodes, materials } = useGLTF("/assets/darth-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_darthvader_VaderHelmetRimmat_0.geometry}
            material={materials.darthvader_VaderHelmetRimmat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_darthvader_VaderBodyArmourmat_0.geometry}
            material={materials.darthvader_VaderBodyArmourmat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_Laser_0.geometry}
            material={materials.Laser}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_Sabel_svart_0.geometry}
            material={materials.Sabel_svart}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_darthvader_VaderCapemat_0.geometry}
            material={materials.darthvader_VaderCapemat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_darthvader_VaderConsolesFlickermat_0.geometry}
            material={materials.darthvader_VaderConsolesFlickermat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DARTH_Sabel_vit_0.geometry}
            material={materials.Sabel_vit}
          />
          <group
            position={[-701.08, 246.68, 200.8]}
            rotation={[-0.03, 0.27, -0.2]}
          />
          <group position={[-200, 200, 200]} rotation={[1.18, -0.36, 0.71]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  );
}

export default Darth;

useGLTF.preload("/assets/darth-transformed.glb");
